version: '3.8'
services:
  torent-stream:
    build: .
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/usr/src/app/data
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
